name: Weekly Run

on:
  schedule:
    - cron: "0 12 * * 3"
  workflow_dispatch:

jobs:
  run-python-script:
    environment: cron-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Run `main.py`
        run: uv run python main.py
        env:
          MODE: ${{ secrets.MODE }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TURSO_DATABASE_NAME: ${{ secrets.TURSO_DATABASE_NAME }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
